"""Persistence for the derived semantic index: entity vectors and the
model metadata they were generated with.

This is deliberately a SEPARATE SQLite file from `memory.db`
(`semantic_index.db`, next to it under `.cortex/`), not a table inside
the canonical store managed by `_store.py`. The semantic index is
DERIVED, OPTIONAL, REBUILDABLE, and REPLACEABLE (see `_semantic.py`'s
module docstring and the A7.4 report): it holds no canonical truth,
nothing here is ever required for a canonical write to succeed, and
deleting this entire file is always safe -- Cortex degrades to
lexical/FTS-only, exactly as if the semantic extra were never installed.
Keeping it in its own file (rather than a table in `memory.db`) makes
that guarantee trivial to reason about and trivial to test: "the
semantic index is missing" is just "this file does not exist", nothing
about the canonical schema version chain in `_store.py` is touched.

This module holds no dependency on `model2vec` or `numpy`: vectors are
opaque `bytes` blobs here, encoded/decoded by `_semantic.py`. That keeps
`_semantic_store.py` importable without the `[semantic]` extra installed
-- it is not imported at all from the normal `import cortex_memory` path
today, but nothing about its own implementation would force that if a
future caller needed to inspect index metadata without loading a model.

Status lifecycle: `begin_rebuild()` clears all vectors and writes a
`semantic_meta` row with `status='building'`, committed immediately.
Embedding the corpus happens OUTSIDE any database transaction (it calls
out to a model, which is slow and not itself transactional). Only after
every vector has been written does `finish_rebuild()` flip the status to
`'ready'` and commit. If the process is interrupted at any point between
`begin_rebuild()` and `finish_rebuild()` (killed, crashes, loses power),
the on-disk state is a `semantic_meta` row stuck at `status='building'`
-- `is_ready()` returns False for that, so the index is correctly
treated as incomplete/unavailable rather than silently used half-built.
"""

from __future__ import annotations

import dataclasses
import sqlite3
from pathlib import Path

from ._errors import CortexStorageError

SEMANTIC_DB_FILENAME = "semantic_index.db"

STATUS_BUILDING = "building"
STATUS_READY = "ready"

_CREATE_META_SQL = """
    CREATE TABLE semantic_meta (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        provider TEXT NOT NULL,
        model_id TEXT NOT NULL,
        model_revision TEXT,
        dimensions INTEGER NOT NULL,
        normalization TEXT NOT NULL,
        created_at TEXT NOT NULL,
        status TEXT NOT NULL
    )
"""

_CREATE_VECTORS_SQL = """
    CREATE TABLE semantic_vectors (
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        vector BLOB NOT NULL,
        PRIMARY KEY (entity_type, entity_id)
    )
"""


def semantic_db_path_for(cortex_dir: Path) -> Path:
    return cortex_dir / SEMANTIC_DB_FILENAME


@dataclasses.dataclass(frozen=True, slots=True)
class SemanticMeta:
    provider: str
    model_id: str
    model_revision: str | None
    dimensions: int
    normalization: str
    created_at: str
    status: str

    def matches(self, *, provider: str, model_id: str, normalization: str) -> bool:
        """Whether an already-built index was generated by the same
        model configuration a caller is about to query with. Checked
        BEFORE the model is loaded (provider/model_id/normalization are
        static constants in `_semantic.py`), so a mismatch is caught
        without paying to load a model that will not be used anyway.
        `dimensions` is deliberately not part of this comparison -- it is
        used later, purely to safely decode stored vector blobs
        (`_semantic.blob_to_vector`); for a fixed `model_id` and
        `normalization` it is expected to be constant, so it adds no
        further discriminating signal here.

        Revision is also intentionally NOT part of this comparison: it
        is recorded for diagnostics/auditing
        (`_semantic.py.resolve_local_revision`), but is often
        unresolvable (multiple cached revisions, no `main` ref) and must
        not itself force an otherwise-matching index to be treated as
        stale."""
        return provider == self.provider and model_id == self.model_id and normalization == self.normalization


class SemanticIndexStore:
    """Boundary around the derived semantic index for a single workspace."""

    def __init__(self, connection: sqlite3.Connection) -> None:
        self._connection = connection

    @classmethod
    def create_or_open(cls, db_path: Path) -> "SemanticIndexStore":
        connection = sqlite3.connect(db_path)
        try:
            _ensure_schema(connection)
        except sqlite3.DatabaseError as exc:
            connection.close()
            raise CortexStorageError(f"Cortex semantic index at {db_path} is corrupted: {exc}") from exc
        except Exception:
            connection.close()
            raise
        return cls(connection)

    @classmethod
    def open_if_exists(cls, db_path: Path) -> "SemanticIndexStore | None":
        if not db_path.exists():
            return None
        return cls.create_or_open(db_path)

    def close(self) -> None:
        self._connection.close()

    def __enter__(self) -> "SemanticIndexStore":
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()

    def meta(self) -> SemanticMeta | None:
        try:
            row = self._connection.execute(
                "SELECT provider, model_id, model_revision, dimensions, normalization, created_at, status "
                "FROM semantic_meta WHERE id = 1"
            ).fetchone()
        except sqlite3.DatabaseError as exc:
            raise CortexStorageError(f"Failed to read Cortex semantic index metadata: {exc}") from exc
        if row is None:
            return None
        return SemanticMeta(*row)

    def is_ready(self) -> bool:
        meta = self.meta()
        return meta is not None and meta.status == STATUS_READY

    def begin_rebuild(
        self,
        *,
        provider: str,
        model_id: str,
        model_revision: str | None,
        dimensions: int,
        normalization: str,
        created_at: str,
    ) -> None:
        """Clear the index and mark it `building`, committed immediately
        so an interruption after this point leaves `is_ready()` False."""
        try:
            with self._connection:
                self._connection.execute("DELETE FROM semantic_vectors")
                self._connection.execute("DELETE FROM semantic_meta WHERE id = 1")
                self._connection.execute(
                    "INSERT INTO semantic_meta "
                    "(id, provider, model_id, model_revision, dimensions, normalization, created_at, status) "
                    "VALUES (1, ?, ?, ?, ?, ?, ?, ?)",
                    (provider, model_id, model_revision, dimensions, normalization, created_at, STATUS_BUILDING),
                )
        except sqlite3.DatabaseError as exc:
            raise CortexStorageError(f"Failed to begin Cortex semantic index rebuild: {exc}") from exc

    def add_vectors(self, entity_type: str, rows: list[tuple[str, bytes]]) -> None:
        """Persist a batch of `(entity_id, vector_blob)` pairs for
        `entity_type`. Must only be called between `begin_rebuild()` and
        `finish_rebuild()`."""
        if not rows:
            return
        try:
            with self._connection:
                self._connection.executemany(
                    "INSERT INTO semantic_vectors (entity_type, entity_id, vector) VALUES (?, ?, ?)",
                    [(entity_type, entity_id, blob) for entity_id, blob in rows],
                )
        except sqlite3.DatabaseError as exc:
            raise CortexStorageError(f"Failed to persist Cortex semantic vectors: {exc}") from exc

    def finish_rebuild(self) -> None:
        try:
            with self._connection:
                self._connection.execute(
                    "UPDATE semantic_meta SET status = ? WHERE id = 1", (STATUS_READY,)
                )
        except sqlite3.DatabaseError as exc:
            raise CortexStorageError(f"Failed to finalize Cortex semantic index rebuild: {exc}") from exc

    def all_vectors(self, entity_type: str) -> list[tuple[str, bytes]]:
        try:
            rows = self._connection.execute(
                "SELECT entity_id, vector FROM semantic_vectors WHERE entity_type = ? ORDER BY entity_id",
                (entity_type,),
            ).fetchall()
        except sqlite3.DatabaseError as exc:
            raise CortexStorageError(f"Failed to read Cortex semantic vectors: {exc}") from exc
        return [(row[0], row[1]) for row in rows]

    def vector_count(self) -> int:
        try:
            (count,) = self._connection.execute("SELECT COUNT(*) FROM semantic_vectors").fetchone()
        except sqlite3.DatabaseError as exc:
            raise CortexStorageError(f"Failed to read Cortex semantic index: {exc}") from exc
        return count


def _table_exists(connection: sqlite3.Connection, name: str) -> bool:
    return (
        connection.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?", (name,)
        ).fetchone()
        is not None
    )


def _ensure_schema(connection: sqlite3.Connection) -> None:
    with connection:
        if not _table_exists(connection, "semantic_meta"):
            connection.execute(_CREATE_META_SQL)
        if not _table_exists(connection, "semantic_vectors"):
            connection.execute(_CREATE_VECTORS_SQL)
